apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-db
  template:
    metadata:
      labels:
        app: account-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: account_db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: account-db-storage
      volumes:
        - name: account-db-storage
          persistentVolumeClaim:
            claimName: account-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: account-db
spec:
  type: ClusterIP
  selector:
    app: account-db
  ports:
    - port: 5432
      targetPort: 5432
